version: '3'

services:
  postgresdb:
    image: postgres:latest
    container_name: julius_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=julius
    ports:
      - "5433:5432"